#!/usr/bin/env python
"""torchgw-bench reporter v1: aggregate results/*.json into docs markdown.

This script is stand-alone. It does NOT import from tracks/ and is NOT
imported by any track. It reads JSON records, groups them by track, and
renders per-tier markdown pages.
"""
from __future__ import annotations

__all__ = [
    "load_results",
    "group_by_track",
    "render_track_section",
    "render_docs_markdown",
    "main",
]

import json
from collections import defaultdict
from pathlib import Path


def load_results(results_dir: Path) -> list[dict]:
    """Scan a results directory for JSON records and return them as a list.

    Lenient: files that are not .json or that fail to parse are silently
    skipped. Missing schema fields are preserved as-is (the renderer handles
    absences with dict.get()).
    """
    results_dir = Path(results_dir)
    if not results_dir.is_dir():
        return []
    records: list[dict] = []
    for path in sorted(results_dir.glob("*.json")):
        try:
            records.append(json.loads(path.read_text()))
        except (json.JSONDecodeError, OSError):
            continue
    return records


def group_by_track(records: list[dict]) -> dict[str, list[dict]]:
    """Bucket records by their 'track' key, with deterministic sorted order."""
    groups: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        groups[r.get("track", "(unknown)")].append(r)
    return {k: groups[k] for k in sorted(groups.keys())}


def _fmt(value, spec: str = "") -> str:
    """Formatting helper that returns '—' for None/missing values."""
    if value is None:
        return "—"
    try:
        return format(value, spec) if spec else str(value)
    except (TypeError, ValueError):
        return str(value)


def render_track_section(track: str, records: list[dict]) -> str:
    """Render one markdown section for a single track."""
    lines: list[str] = []

    tier = track.split("/", 1)[0].capitalize() if "/" in track else "Unknown"
    lines.append(f"## {tier} Track: `{track}`")
    lines.append("")

    ds_name = next(
        (r.get("dataset", {}).get("name") for r in records if r.get("dataset", {}).get("name")),
        None,
    )
    if ds_name:
        lines.append(f"**Dataset:** `{ds_name}`")
    n_source = next(
        (r.get("dataset", {}).get("n_source") for r in records if r.get("dataset", {}).get("n_source")),
        None,
    )
    n_target = next(
        (r.get("dataset", {}).get("n_target") for r in records if r.get("dataset", {}).get("n_target")),
        None,
    )
    if n_source and n_target:
        lines.append(f"**Scale:** N={n_source}, K={n_target}")
    lines.append("")

    host_gpu = next(
        (r.get("host", {}).get("gpu") for r in records
         if r.get("status") == "ok" and r.get("host", {}).get("gpu")),
        None,
    )
    if host_gpu:
        lines.append(f"**Host:** `{host_gpu}`")
        lines.append("")

    lines.append("| Solver | Status | GW cost | Spearman | Wall (s) | GPU peak (GB) | Iterations |")
    lines.append("|---|:---:|---:|---:|---:|---:|---:|")
    for r in records:
        solver = r.get("solver", "?")
        status = r.get("status", "?")
        metrics = r.get("metrics", {}) or {}
        correctness = metrics.get("correctness", {}) or {}
        task = metrics.get("task", {}) or {}
        efficiency = metrics.get("efficiency", {}) or {}

        status_cell = {"ok": "✓", "fail": "✗ FAIL", "skip": "⊘ skip"}.get(status, status)

        row = (
            f"| `{solver}` | {status_cell} | "
            f"{_fmt(correctness.get('gw_cost'), '.4f')} | "
            f"{_fmt(task.get('spearman_arclen'), '.4f')} | "
            f"{_fmt(efficiency.get('wall_s'), '.2f')} | "
            f"{_fmt(efficiency.get('gpu_peak_gb'), '.2f')} | "
            f"{_fmt(efficiency.get('iterations'))} |"
        )
        lines.append(row)

        if status == "fail" and r.get("error"):
            lines.append(f"|     | error: `{r['error']}` |||||||")

    lines.append("")
    return "\n".join(lines)


def render_docs_markdown(records: list[dict], tier: str) -> str:
    """Render the top-level markdown for a tier."""
    tier_lc = tier.lower()
    filtered = [r for r in records if str(r.get("track", "")).startswith(f"{tier_lc}/")]
    groups = group_by_track(filtered)

    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by scripts/make_report.py — do not hand edit -->")
    lines.append("")
    lines.append(f"# {tier.capitalize()} tier benchmark")
    lines.append("")
    lines.append(
        f"This page aggregates results from `results/*.json` that belong to "
        f"the `{tier_lc}/` tier. Regenerate with:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append(f"python scripts/make_report.py --format docs --out docs/")
    lines.append("```")
    lines.append("")

    if not groups:
        lines.append("_No records found for this tier yet._")
        lines.append("")
        return "\n".join(lines)

    for track, track_records in groups.items():
        lines.append(render_track_section(track, track_records))

    return "\n".join(lines)


def main() -> None:
    import argparse
    import sys

    ap = argparse.ArgumentParser(description="torchgw-bench reporter v1")
    ap.add_argument("--format", required=True, choices=["docs"],
                    help="Output format (only 'docs' is supported in v1)")
    ap.add_argument("--results", type=Path, default=Path("results"),
                    help="Directory to scan for JSON records")
    ap.add_argument("--out", type=Path, default=Path("docs"),
                    help="Directory to write rendered markdown into")
    ap.add_argument("--tier", default="all",
                    help="Which tier to render: core | extended | gallery | all")
    args = ap.parse_args()

    records = load_results(args.results)
    if not records:
        print(f"[reporter] no records found in {args.results}/", file=sys.stderr)

    args.out.mkdir(parents=True, exist_ok=True)

    tiers = ["core", "extended", "gallery"] if args.tier == "all" else [args.tier]
    for tier in tiers:
        md = render_docs_markdown(records, tier=tier)
        dest = args.out / f"tier_{tier}.md"
        dest.write_text(md)
        print(f"[reporter] wrote {dest}")


if __name__ == "__main__":
    main()
